# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: adventr
    url: 'adventr/'
    weight: 10
  - name: Solutions
    url: 'solutions/'
    weight: 20
  - name: Data
    url: 'data/'
    weight: 30
  - name: Book
    url: 'book/'
    weight: 40
  - name: Me
    url: "#about"
    weight: 50
